# Generated by Django 3.2.5 on 2021-07-08 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('game_date', models.DateField()),
                ('time_class', models.CharField(max_length=10)),
                ('opponent_color', models.CharField(max_length=1)),
                ('opponent_rating', models.PositiveIntegerField()),
                ('opponent_username', models.CharField(max_length=50)),
                ('my_rating', models.PositiveIntegerField()),
                ('pgn', models.TextField()),
            ],
            options={
                'db_table': 'game',
            },
        ),
    ]
