# Generated by Django 3.2.5 on 2021-07-08 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_class', models.CharField(max_length=10)),
                ('opponent_color', models.CharField(max_length=1)),
                ('opponent_username', models.CharField(max_length=1)),
            ],
        ),
    ]
