# Generated by Django 3.2.5 on 2021-07-14 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='opponent_color',
        ),
    ]
