# Generated by Django 3.2.5 on 2021-07-14 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_remove_game_opponent_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='my_color',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
