# Generated by Django 3.2.5 on 2021-07-15 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_game_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='opponent_country',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
