# Generated by Django 4.1.2 on 2022-10-08 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_game_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='my_accuracy',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='opponent_accuracy',
            field=models.FloatField(null=True),
        ),
    ]
