# Generated by Django 4.1.2 on 2022-10-08 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_game_my_accuracy_game_opponent_accuracy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='pgn',
            field=models.TextField(db_collation='utf8_general_ci'),
        ),
    ]
