# Generated by Django 4.1.2 on 2022-10-08 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_alter_game_pgn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='clk',
            field=models.CharField(max_length=12),
        ),
    ]
