# Generated by Django 3.2.5 on 2021-07-19 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_game_result_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='eco',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='eco_url',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='game_end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='game_end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='game_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='termination',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_date',
            field=models.DateField(null=True),
        ),
    ]
