# Generated by Django 4.1.2 on 2022-10-09 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_alter_move_clk'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='site',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='url',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='variant',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
