# Generated by Django 4.1.3 on 2023-01-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_game_site_game_url_game_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='time_control',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='time_class',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
