#https://docs.docker.com/samples/django/

version: "3.9"

services:
  server:
    build:
      context: ./docker_images/nginx
      args:
        NGINX_VERSION: 1.18
    ports:
      - "80:8000"
      - "443:8443"
    volumes:
      - .:/var/www/mchess
      - ssldata:/etc/nginx/certs
    depends_on:
      - db
      - web
  web:
    build:
      context: ./docker_images/python
      args:
        PYTHON_VERSION: 3.8.10
    volumes:
      - .:/code
    command: bash -c "uwsgi --ini mchess_uwsgi.ini"
    depends_on:
      - db
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mchess
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    volumes:
      - dbdata:/var/lib/mysql
volumes:
  dbdata:
  ssldata: